### ISSUE TITLE
Impossible de modifier un lieu

### ISSUE THREAD

**Issue by sebastienbruel** [betagouv/pass-culture-pro#122]
Erreur serveur. Tentez de rafraîchir la page.

**Comment by arnoo** [comment]
Bonjour,
Désolé, nous voyons seulement votre ticket ! Nous n'avons pas utilisé la fonctionnalité tickets de Github sur ce dépôt, et n'avions manifestement pas de notifications. Le problème que vous signaliez avait toutefois été repéré par ailleurs, et nous l'avons corrigé.
Merci pour votre aide et désolé encore pour le délai.
